package com.example.aurini.greendaotest.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ARTICLE".
 */
@Entity
public class Article {

    @Id
    private Long id;
    private Long  ariticle_id;
    private String category;
    private String text_comment;
    private String img_link_server;
    private String img_link_local;
    private Integer week_id;
    private String weblink;
    private Boolean show_enabled;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Article() {
    }

    public Article(Long id) {
        this.id = id;
    }

    @Generated
    public Article(Long id, Long  ariticle_id, String category, String text_comment, String img_link_server, String img_link_local, Integer week_id, String weblink, Boolean show_enabled) {
        this.id = id;
        this. ariticle_id =  ariticle_id;
        this.category = category;
        this.text_comment = text_comment;
        this.img_link_server = img_link_server;
        this.img_link_local = img_link_local;
        this.week_id = week_id;
        this.weblink = weblink;
        this.show_enabled = show_enabled;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long get Ariticle_id() {
        return  ariticle_id;
    }

    public void set Ariticle_id(Long  ariticle_id) {
        this. ariticle_id =  ariticle_id;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getText_comment() {
        return text_comment;
    }

    public void setText_comment(String text_comment) {
        this.text_comment = text_comment;
    }

    public String getImg_link_server() {
        return img_link_server;
    }

    public void setImg_link_server(String img_link_server) {
        this.img_link_server = img_link_server;
    }

    public String getImg_link_local() {
        return img_link_local;
    }

    public void setImg_link_local(String img_link_local) {
        this.img_link_local = img_link_local;
    }

    public Integer getWeek_id() {
        return week_id;
    }

    public void setWeek_id(Integer week_id) {
        this.week_id = week_id;
    }

    public String getWeblink() {
        return weblink;
    }

    public void setWeblink(String weblink) {
        this.weblink = weblink;
    }

    public Boolean getShow_enabled() {
        return show_enabled;
    }

    public void setShow_enabled(Boolean show_enabled) {
        this.show_enabled = show_enabled;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
