package com.example.aurini.greendaotest.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.aurini.greendaotest.db.User;
import com.example.aurini.greendaotest.db.Article;
import com.example.aurini.greendaotest.db.Diary;
import com.example.aurini.greendaotest.db.Food;
import com.example.aurini.greendaotest.db.Food_Category;

import com.example.aurini.greendaotest.db.UserDao;
import com.example.aurini.greendaotest.db.ArticleDao;
import com.example.aurini.greendaotest.db.DiaryDao;
import com.example.aurini.greendaotest.db.FoodDao;
import com.example.aurini.greendaotest.db.Food_CategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig articleDaoConfig;
    private final DaoConfig diaryDaoConfig;
    private final DaoConfig foodDaoConfig;
    private final DaoConfig food_CategoryDaoConfig;

    private final UserDao userDao;
    private final ArticleDao articleDao;
    private final DiaryDao diaryDao;
    private final FoodDao foodDao;
    private final Food_CategoryDao food_CategoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        diaryDaoConfig = daoConfigMap.get(DiaryDao.class).clone();
        diaryDaoConfig.initIdentityScope(type);

        foodDaoConfig = daoConfigMap.get(FoodDao.class).clone();
        foodDaoConfig.initIdentityScope(type);

        food_CategoryDaoConfig = daoConfigMap.get(Food_CategoryDao.class).clone();
        food_CategoryDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);
        diaryDao = new DiaryDao(diaryDaoConfig, this);
        foodDao = new FoodDao(foodDaoConfig, this);
        food_CategoryDao = new Food_CategoryDao(food_CategoryDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Article.class, articleDao);
        registerDao(Diary.class, diaryDao);
        registerDao(Food.class, foodDao);
        registerDao(Food_Category.class, food_CategoryDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        articleDaoConfig.clearIdentityScope();
        diaryDaoConfig.clearIdentityScope();
        foodDaoConfig.clearIdentityScope();
        food_CategoryDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public DiaryDao getDiaryDao() {
        return diaryDao;
    }

    public FoodDao getFoodDao() {
        return foodDao;
    }

    public Food_CategoryDao getFood_CategoryDao() {
        return food_CategoryDao;
    }

}
