package com.example.aurini.greendaotest.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FOOD".
 */
@Entity
public class Food {

    @Id
    private Long id;
    private Long id_server;
    private Long  category_id;
    private String  desc;
    private String absolute_name;
    private String unit;
    private Float increament_value;
    private Float cal_per_unit_curb;
    private Float cal_per_unit_protien;
    private Float cal_per_unit_fat;
    private Float cal_per_unit_total;;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Food() {
    }

    public Food(Long id) {
        this.id = id;
    }

    @Generated
    public Food(Long id, Long id_server, Long  category_id, String  desc, String absolute_name, String unit, Float increament_value, Float cal_per_unit_curb, Float cal_per_unit_protien, Float cal_per_unit_fat, Float cal_per_unit_total;) {
        this.id = id;
        this.id_server = id_server;
        this. category_id =  category_id;
        this. desc =  desc;
        this.absolute_name = absolute_name;
        this.unit = unit;
        this.increament_value = increament_value;
        this.cal_per_unit_curb = cal_per_unit_curb;
        this.cal_per_unit_protien = cal_per_unit_protien;
        this.cal_per_unit_fat = cal_per_unit_fat;
        this.cal_per_unit_total; = cal_per_unit_total;;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_server() {
        return id_server;
    }

    public void setId_server(Long id_server) {
        this.id_server = id_server;
    }

    public Long get Category_id() {
        return  category_id;
    }

    public void set Category_id(Long  category_id) {
        this. category_id =  category_id;
    }

    public String get Desc() {
        return  desc;
    }

    public void set Desc(String  desc) {
        this. desc =  desc;
    }

    public String getAbsolute_name() {
        return absolute_name;
    }

    public void setAbsolute_name(String absolute_name) {
        this.absolute_name = absolute_name;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Float getIncreament_value() {
        return increament_value;
    }

    public void setIncreament_value(Float increament_value) {
        this.increament_value = increament_value;
    }

    public Float getCal_per_unit_curb() {
        return cal_per_unit_curb;
    }

    public void setCal_per_unit_curb(Float cal_per_unit_curb) {
        this.cal_per_unit_curb = cal_per_unit_curb;
    }

    public Float getCal_per_unit_protien() {
        return cal_per_unit_protien;
    }

    public void setCal_per_unit_protien(Float cal_per_unit_protien) {
        this.cal_per_unit_protien = cal_per_unit_protien;
    }

    public Float getCal_per_unit_fat() {
        return cal_per_unit_fat;
    }

    public void setCal_per_unit_fat(Float cal_per_unit_fat) {
        this.cal_per_unit_fat = cal_per_unit_fat;
    }

    public Float getCal_per_unit_total;() {
        return cal_per_unit_total;;
    }

    public void setCal_per_unit_total;(Float cal_per_unit_total;) {
        this.cal_per_unit_total; = cal_per_unit_total;;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
