package com.example.aurini.greendaotest.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "FOOD__CATEGORY".
 */
@Entity
public class Food_Category {
    private Long id;
    private Long id_server;
    private String food_category_name;
    private Boolean header_open;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Food_Category() {
    }

    @Generated
    public Food_Category(Long id, Long id_server, String food_category_name, Boolean header_open) {
        this.id = id;
        this.id_server = id_server;
        this.food_category_name = food_category_name;
        this.header_open = header_open;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId_server() {
        return id_server;
    }

    public void setId_server(Long id_server) {
        this.id_server = id_server;
    }

    public String getFood_category_name() {
        return food_category_name;
    }

    public void setFood_category_name(String food_category_name) {
        this.food_category_name = food_category_name;
    }

    public Boolean getHeader_open() {
        return header_open;
    }

    public void setHeader_open(Boolean header_open) {
        this.header_open = header_open;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
