package com.example.aurini.greendaotest.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id
    private Long id;
    private long user_id;
    private String token;
    private String name;
    private String email;
    private String phone;
    private java.util.Date lmp;
    private String photoPath;
    private String photoLink;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, long user_id, String token, String name, String email, String phone, java.util.Date lmp, String photoPath, String photoLink) {
        this.id = id;
        this.user_id = user_id;
        this.token = token;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.lmp = lmp;
        this.photoPath = photoPath;
        this.photoLink = photoLink;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUser_id() {
        return user_id;
    }

    public void setUser_id(long user_id) {
        this.user_id = user_id;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public java.util.Date getLmp() {
        return lmp;
    }

    public void setLmp(java.util.Date lmp) {
        this.lmp = lmp;
    }

    public String getPhotoPath() {
        return photoPath;
    }

    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    public String getPhotoLink() {
        return photoLink;
    }

    public void setPhotoLink(String photoLink) {
        this.photoLink = photoLink;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
